apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBuLqg4OGMZfnMf757GKBJ8pqSE2KV+Z+IGXggLA2ZKpRyrN5O8KuNvlUKm6HjgMCLRXI5wHCZoU6OQDvytD0QaosXeaj7DLS+YMkBBbBKG50R0XU56taM0vIDArRJ47rQzBpTxJzg28+XfX6FRM6nB6bMWtyz57y5qaCQAMX/8HJ4SQZboZV6YB48mv0eHdaVxRJeh8dtJG13GI/RczcC+SA2jn3q0bttRQFtBETQ0lCxJLBRsEC0h+ml0Asq2Br0UhpOb+MCHAP6U0zswWmo/5QNFEXhZyp8WN7qkjNcf5Uy7//y+fe6cFcAVzVXJ03K3ekdUxUpqvw/W8Es6b7C1mbRrG1HPgnrCDW/kK7792uCeVF5JaY2EEcl0h35sytoMZ8th8MwkFt39uv1VKYzpTQFyFWk8pCUbkf4a0myREc0uhJwqr2CNasx3D36VQ4KwftbiZnCKwVMgoq5paZoHZqWGN2h4NtotX8LCFNU7IO38emWQGH4deTx6geDAPX27H0ufou07c4f+j9lZccau+cP8F18A4giilJfUfaxHI/JcbcQADdbhyirG4eYEVobNqgDPFI7wYRpopsmZG89OZMF920vhV+Dtdq85MHSVdeONWqSoo0jjR55Cb4vFx4pNd6cLdGnBNEYqUhTizGhyEoUZOw30+pxJ2ILzOykq5ORwmEr+Z6SBVpwqgcveVu9bzibeRgoIidsduXCGvjysgmKvw4J6epP1dTocPS/z2R/2KWuYGocDYH5GkU6MPBgtIMkOco65qeX7GYjLJo47tG5gNZyqgRXMtmmn8uWr7e0ltKdoq7OW173fHZ4rIeTMl/8jkNHuapPwxyz4kbfs3C2LBejP/BiRAHLyTbV9JM+kYW/vrhbHHAr7rjQST0kozp/XG6+Yq7ARZQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

