apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBbHM6QAcrmQLPn3/ZZTULg1MlT0ZULTvFBnBoRulkh/Ps5Tzu+b1sMUVurnhOQ0W+XAgipIMQTT/c96hbSjs873m5/L9lPqeaBBUS5dy6qh5XfqKPUdS1MnRQPZAgc5UjXOWbQ3vdddy8J/EibwGaao7NretnSLu6xSUbkMqnOFWve3ct4Nhj1tAluZIUVRBr8zSizLlkNPTDQASQ51TnpniADiDlIXWQ9oqJrGW3t0Rpx+/2+Ls6ExwrS5zH0ljk4f+pojGQfBwFWVv2wefuBdjz8Fg+VEkzrWtea9CXsJaoOCWlgbiZg0W5CX7fa29L775vFMkcmMr/GKEsdP0yj3UV9rEY1KDBqd41oHgoNeB81CMVXAy6tza7JWnOzBKTAC60yo8dj0v2mjNUuWVG2zey93woAO8/bsyla7B/J7e1qize6mCAaWJ49pa/+4u6o1tFwS7o+RpHoV072X8erHvA1reFUu5euC6rrMr258wQFGYHpbZsHUftSjw1FGuBnm1pSgIibHOEX/yAdb9yDJqBxpWJlF7V92t30NIZFSo7BXlbYso/2GhwSPZrDWUVD9p8HZWCfh53Tkq+3Y/hXPMagZf51rg5o5k2/mxCYJXIUC6m6yfigMaV7TDZw0An5Z8HCgYNkQEeD1r3hqvwJMBEywjFYUV2TYqRW6qpegEcXxREQPO1rRvHN4yblWYk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

