apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCC4GPyMKwfIFA7TqBmaC/zXTTR86R13ENzXMWs6K7mhz5eBLb4IC8TWbaAUJjXOLlxSTRkCf1BKvJ+1hlXPjSKmxm0U+Yc3xjpi5WMNWsyUynadVX2oL59bQSSHLdCdiIuGYMyjVw9s/yYWPMJai7d8+9563RMAW+0gaWAvFittBmB403KZ+gN+x9klenOOdyMw6yXDj/v1JSHCiT5TnhUhy4HFxgsUG92JZpR2mOxu7FaCsZyrkHmii0YQVtbkgF2cZ4syQHokf+oPBDn5sbrSzOuuTC3xAXxCp8ouZRL+snapLpzN1f4lsIX+ZZl0ZDGidX8wqHeOgzdE/BYiCZb6oQLpbkMegajlpvPVBdqzObCafp3aRrrZBFYKJH+aidWWHSSUTRyhRtb1hbGauqKMYUXSn4wydpwUFcFdXyFxJ31W85H38B2srAGrqEs7j1Rf6nB30vkscvgCrRmN7z2IoLM/O812dRatcgiMKk1pKj6uzyKMKbJHJxn0+EoJrxusLME8GciMFfJFZUG3PnfTJDrvJhIbIol6WSC8Mgg83eDUV7mpW5CrW7JNtOURy43Z2cPc6Lenq+kCqTLHaPvqZXQ+RUPcXbNDkgaxwe6T3XwfRhZb97eEaDA0xN30+j967Du/6cxvbkikKg7eqZzBzhIA+ocL5KNTEDXqQaAWSeCdGsHTFtVxloDfz3zJO5hX0XK6i3Z8EEx57S5CyF1KXuK+uqLj7cSFbzjAeIXVmsgwKgtDa8/
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

