apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCcY7Arpilk+KccUvkuPvfWNg1nuosRRKiP5HYfa5p+LGUv+FEvOwDgO+lqIZBH+J3QaJAsrcm9Dcz4n9Z5QWj34mE6GOQnno1HXDewa9W9v7W74b4X7I6OWsGHTcDd2ijdFV/mb93cYYqigMq+RTlPbIx50cA04G6jjqLW29zbbzBpiSc7bqLjsYyqIYOtn64iP+qu1kLEWv2mFsKOn89IRWbXUnOESp6SJCVgR+6y6eBjuAyrVe7s8txJU/Rfuq7Ve7zZKfESRrJ6bcnDt5FDAmAilKOOHb1Zi4MNOA4zdjBZf1+rYO7sZhuwob3ZEJfoOP+ep2YzkLgsbuo2QkyLCpYBrgl+6Dm8kQtjAHMFsoGUbYmftqtWgmQtwNx0r5VilavHlXwErzwT3ZduAj1xFQ95KNZ+2+dIkaumTju7D3aCeCzcjj4GpmNf3f2bS6nF5UpTEJPfYxrRm3hX/RPNrVWY1eRTAhkWqkwm6l5a9ZBmRuBIYAfxpp4F9ro6bXD9ctvOQAkfOuNKgXoEuued06fyaBoL70OQFZg888QjxXp4CQzi10wTNH5xF6uawX6GkFOA5CoPeNvh1TNs7vr+9NRG2yPsvMJuzGOPVlFGUCkFGxZiPdkNZ5uXrjHFPpeWkLHuACryKh1ibEOs9eyzaRRqSqVvULzG97wjj0diX3swqCuxAPQysRMkVwwEVkU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

